//
//  UIFont+BTMAdditions.swift
//
//  Generated by Zeplin on 4/22/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func btmProjectHeaderTitleFont() -> UIFont {
		return UIFont.systemFont(ofSize: 60.0, weight: UIFontWeightUltraLight)
	}

	class func btmTaskNameFont() -> UIFont {
		return UIFont.systemFont(ofSize: 40.0, weight: UIFontWeightBold)
	}

	class func btmTaskNotesFont() -> UIFont {
		return UIFont.systemFont(ofSize: 40.0, weight: UIFontWeightUltraLight)
	}

	class func btmProjectTitleFont() -> UIFont {
		return UIFont.systemFont(ofSize: 20.0, weight: UIFontWeightLight)
	}

	class func btmActionButtonFont() -> UIFont {
		return UIFont.systemFont(ofSize: 20.0, weight: UIFontWeightUltraLight)
	}
}
